FROM python:3.12-slim

COPY . /app

WORKDIR /app

RUN python -m pip install --upgrade pip && \
    pip install -r requirements_cpu.txt && \
    pip install -r requirements.txt 

ENV GIT_PYTHON_REFRESH=quiet


CMD dvc pull models/best_model.pt && python -m src.training.evaluate
