stages:
  training_data_prep:
    cmd: python -m src.data.preprocess
    outs:
    - data/wikitext-train.txt
    - data/wikitext-val.txt
    - data/wikitext-test.txt
    
  upload_data:
    cmd: dvc push data/wikitext-train.txt data/wikitext-val.txt data/wikitext-test.txt
    deps:
    - data/wikitext-train.txt
    - data/wikitext-val.txt
    - data/wikitext-test.txt
  
  training:
    cmd: python -m src.training.train
    deps:
    - src/training/train.py
    - data/wikitext-train.txt
    - data/wikitext-val.txt
    outs:
    - models/candidate/trained_model.pt

  evaluate:
    cmd: python -m src.training.evaluate --model-path models/candidate/trained_model.pt --output-path models/candidate/metrics.json --config-path models/candidate/config.yaml
    deps:
    - src/training/evaluate.py
    - data/wikitext-test.txt
    - models/candidate/trained_model.pt

  upload_model:
    cmd: dvc push models/candidate/trained_model.pt
    deps:
    - models/candidate/trained_model.pt


  git_commit:
    cmd: git add . && git commit -m "DVC pipeline update" || echo "No changes to commit"
    deps:
    - models/candidate/trained_model.pt
    - models/candidate/metrics.json
    - models/candidate/config.yaml